# Generated by Django 2.1.7 on 2019-02-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(default='/static/images/cards/default.jpg', upload_to='static/images/cards/')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
