# Generated by Django 2.1.7 on 2019-02-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.AddField(
            model_name='card',
            name='publications',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
