# Generated by Django 2.1.7 on 2019-02-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190218_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='publications',
            new_name='categories',
        ),
    ]
